#!/bin/bash

WD="$(pwd)"

function linker {
	# hlink source, destination
	"$WD/hlink" "$1" "$2"
}

function unlinker {
	# hlink -u destination
	"$WD/hlink" -u "$1"
}


if [ ANDROID_SDK_HOME == "" ];
then
	HOMEDIR="$HOME/.android"
else
	HOMEDIR="$ANDROID_SDK_HOME"
fi

if [ ! -d "ini" ];
then
	mkdir ini 2>&1
fi

cd avd

if [ $# -gt 1 ]; then
	FILELIST="$@"
else
	read -p "Update SDK? (y/n): " REPLY
	if [ "$REPLY" == "y" ]; then
		../updatesdk
	fi

	FILELIST="$(ls *.ini)"

	unlinker "$HOME/.android/devices.xml"

	# clean old links if they exist
	for FILE in FILELIST
	do
		unlinker "$HOME/.android/avd/$FILE"
	done
fi

linker "$WD/devices.xml" "$HOME/.android/devices.xml"

for FILE in $FILELIST
do
	BASE="${FILE%.*}"
	echo -e "Cleaning path in $FILE ..."
	sed 's|path=.*/.android/avd|path='"$WD"'/avd|g' "$FILE" > "../ini/$FILE"

	echo -e "Linking to $BASE from .android/avd ..."
	linker "$WD/ini/$FILE" "$HOME/.android/avd/$FILE"

	# repairs path issues in the disk images
	echo -e "Repairing any issues in config.ini for $BASE ..."
	android update avd -n "$BASE"

	echo -e "Done."
	echo ""
done

cd "$WD"